src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'Il existe déjà un compte avec cet email.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\OneToMany(targetEntity: Vente::class, mappedBy: 'vendeur')]
    private Collection $ventes;

    #[ORM\OneToMany(targetEntity: Vente::class, mappedBy: 'acheteur')]
    private Collection $achats;

    #[ORM\OneToMany(targetEntity: Location::class, mappedBy: 'locataire')]
    private Collection $locations;

    #[ORM\OneToMany(targetEntity: Voiture::class, mappedBy: 'proprietaire')]
    private Collection $voitures;

    #[ORM\OneToMany(targetEntity: Message::class, mappedBy: 'expediteur')]
    private Collection $messagesExpediteur;

    #[ORM\OneToMany(targetEntity: Message::class, mappedBy: 'destinataire')]
    private Collection $messagesDestinataire;

    #[ORM\OneToMany(targetEntity: Conversation::class, mappedBy: 'firstUser')]
    private Collection $conversations;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imageProfil = null;

    public function __construct()
    {
        $this->ventes = new ArrayCollection();
        $this->achats = new ArrayCollection();
        $this->locations = new ArrayCollection();
        $this->voitures = new ArrayCollection();
        $this->messagesExpediteur = new ArrayCollection();
        $this->messagesDestinataire = new ArrayCollection();
        $this->conversations = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    /**
     * @return Collection<int, Vente>
     */
    public function getVentes(): Collection
    {
        return $this->ventes;
    }

    public function addVente(Vente $vente): static
    {
        if (!$this->ventes->contains($vente)) {
            $this->ventes->add($vente);
            $vente->setVendeur($this);
        }

        return $this;
    }

    public function removeVente(Vente $vente): static
    {
        if ($this->ventes->removeElement($vente)) {
            // set the owning side to null (unless already changed)
            if ($vente->getVendeur() === $this) {
                $vente->setVendeur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Vente>
     */
    public function getAchats(): Collection
    {
        return $this->achats;
    }

    public function addAchat(Vente $achat): static
    {
        if (!$this->achats->contains($achat)) {
            $this->achats->add($achat);
            $achat->setAcheteur($this);
        }

        return $this;
    }

    public function removeAchat(Vente $achat): static
    {
        if ($this->achats->removeElement($achat)) {
            // set the owning side to null (unless already changed)
            if ($achat->getAcheteur() === $this) {
                $achat->setAcheteur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Location>
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): static
    {
        if (!$this->locations->contains($location)) {
            $this->locations->add($location);
            $location->setLocataire($this);
        }

        return $this;
    }

    public function removeLocation(Location $location): static
    {
        if ($this->locations->removeElement($location)) {
            // set the owning side to null (unless already changed)
            if ($location->getLocataire() === $this) {
                $location->setLocataire(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Voiture>
     */
    public function getVoitures(): Collection
    {
        return $this->voitures;
    }

    public function addVoiture(Voiture $voiture): static
    {
        if (!$this->voitures->contains($voiture)) {
            $this->voitures->add($voiture);
            $voiture->setProprietaire($this);
        }

        return $this;
    }

    public function removeVoiture(Voiture $voiture): static
    {
        if ($this->voitures->removeElement($voiture)) {
            // set the owning side to null (unless already changed)
            if ($voiture->getProprietaire() === $this) {
                $voiture->setProprietaire(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessagesExpediteur(): Collection
    {
        return $this->messagesExpediteur;
    }

    public function addMessagesExpediteur(Message $messagesExpediteur): static
    {
        if (!$this->messagesExpediteur->contains($messagesExpediteur)) {
            $this->messagesExpediteur->add($messagesExpediteur);
            $messagesExpediteur->setExpediteur($this);
        }

        return $this;
    }

    public function removeMessagesExpediteur(Message $messagesExpediteur): static
    {
        if ($this->messagesExpediteur->removeElement($messagesExpediteur)) {
            // set the owning side to null (unless already changed)
            if ($messagesExpediteur->getExpediteur() === $this) {
                $messagesExpediteur->setExpediteur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessagesDestinataire(): Collection
    {
        return $this->messagesDestinataire;
    }

    public function addMessagesDestinataire(Message $messagesDestinataire): static
    {
        if (!$this->messagesDestinataire->contains($messagesDestinataire)) {
            $this->messagesDestinataire->add($messagesDestinataire);
            $messagesDestinataire->setDestinataire($this);
        }

        return $this;
    }

    public function removeMessagesDestinataire(Message $messagesDestinataire): static
    {
        if ($this->messagesDestinataire->removeElement($messagesDestinataire)) {
            // set the owning side to null (unless already changed)
            if ($messagesDestinataire->getDestinataire() === $this) {
                $messagesDestinataire->setDestinataire(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Conversation>
     */
    public function getConversations(): Collection
    {
        return $this->conversations;
    }

    public function addConversation(Conversation $conversation): static
    {
        if (!$this->conversations->contains($conversation)) {
            $this->conversations->add($conversation);
            $conversation->setFirstUser($this);
        }

        return $this;
    }

    public function removeConversation(Conversation $conversation): static
    {
        if ($this->conversations->removeElement($conversation)) {
            // set the owning side to null (unless already changed)
            if ($conversation->getFirstUser() === $this) {
                $conversation->setFirstUser(null);
            }
        }

        return $this;
    }

    public function getImageProfil(): ?string
    {
        return $this->imageProfil;
    }

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Form\ProfilImageType;
use App\Repository\AgenceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class ProfilController extends AbstractController
{
    #[Route('/profil', name: 'app_profil')]
    public function index(AgenceRepository $agenceRepository): Response
    {
        // Récupérer l'utilisateur actuel
        $utilisateur = $this->getUser();
        if(!$utilisateur){
            return $this->redirectToRoute('app_login');
        }

        // Récupérer les ventes de l'utilisateur
        $ventes = $utilisateur->getVentes();

        // Récupérer les achats de l'utilisateur
        $achats = $utilisateur->getAchats();

        // Récupérer tous les véhicules de l'utilisateur
        $voitures = $utilisateur->getVoitures();

        $locations = $utilisateur->getLocations();

        $anciennesLocations = [];
        $nouvellesLocations = [];

        $dateDuJour = new \DateTime();

        foreach ($locations as $location) {
            if ($location->getDateFinLocation() < $dateDuJour) {
                $anciennesLocations[] = $location;
            } else {
                $nouvellesLocations[] = $location;
            }
        }

        $agences = $agenceRepository->findAllExceptDefault();

        return $this->render('profil/index.html.twig', [
            'ventes' => $ventes,
            'achats' => $achats,
            'voitures' => $voitures,
            'anciennesLocations' => $anciennesLocations,
            'nouvellesLocations' => $nouvellesLocations,
            'agences' => $agences,
            'dateDuJour' => $dateDuJour,
        ]);
    }

    #[Route('/profil/modifier', name: 'app_profil_modifier')]
    public function edit(Request $request, EntityManagerInterface $entityManager): Response
    {
        $utilisateur = $this->getUser();
        if(!$utilisateur){
            return $this->redirectToRoute('app_login');
        }
        $form = $this->createForm(ProfilImageType::class, $utilisateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('imageProfil')->getData();

            // Si une image a été téléchargée
            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $newFilename = $originalFilename.'-'.uniqid().'.'.$imageFile->guessExtension();

                // Déplacez le fichier dans le répertoire où les images de profil sont stockées
                try {
                    $imageFile->move(
                        $this->getParameter('upload_directory_3'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // Gérer l'erreur si le téléchargement échoue
                }

                // Mettez à jour le chemin de l'image de profil de l'utilisateur
                $utilisateur->setImageProfil($newFilename);
            }
            $entityManager->persist($utilisateur);
            $entityManager->flush();

            return $this->redirectToRoute('app_profil');
        }

        return $this->render('profil/modifier.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Profil{% endblock %}

{% block body %}
    <main>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2 class="mt-4">
                        {% if app.user %}
                            {% if app.user.imageProfil %}
                                <img src="{{ asset('img/profil/' ~ app.user.imageProfil) }}" alt="Photo de profil" class="profile-image-grand">
                            {% endif %}
                        {% endif %}
                        Profil de {{ app.user.firstName }}
                    </h2>
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Informations de l'utilisateur :</h4>
                            <p class="card-text">Prénom : {{ app.user.firstName }}</p>
                            <p class="card-text">Email : {{ app.user.email }}</p>

                            <h4 class="card-title">Ajouter une image de profil :</h4>
                            <a href="{{ path('app_profil_modifier') }}">Ajout</a>

                            <h4 class="card-title">Messagerie :</h4>
                            <a href="{{ path('app_message') }}">Voir mes messages</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <h2 class="mt-4">Véhicules en vente :</h2>
                    <ul class="list-group">
                        {% if voitures|length >0 %}
                            {% for voiture in voitures %}
                                <li class="list-group-item">
                                    {{ voiture.marque }} {{ voiture.modele }} - Agence actuelle : {{ voiture.agence.adresse }}
                                    <form action="{{ path('app_changer_agence_vente', {'id': voiture.id}) }}" method="post" class="mt-2">
                                        <select name="nouvelle_agence" class="form-control">
                                            {% for agence in agences %}
                                                <option value="{{ agence.id }}">{{ agence.adresse }}</option>
                                            {% endfor %}
                                        </select>
                                        <button type="submit" class="btn btn-primary mt-2">Changer l'agence de vente</button>
                                    </form>
                                    <a href="{{ path('app_vente_supprimer', { 'id': voiture.id }) }}" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cette vente ?')" class="btn btn-danger mt-2">Supprimer</a>
                                </li>
                            {% endfor %}
                        {% else %}
                            <li class="list-group-item">Aucune vente en cours.</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h2 class="mt-4">Anciennes ventes de l'utilisateur :</h2>
                    <ul class="list-group">
                        {% if ventes|length > 0 %}
                            {% for vente in ventes %}
                                <li class="list-group-item">Date de vente : {{ vente.dateVente|date('Y-m-d') }} - Prix de vente : {{ vente.prixVente }} - Véhicule vendu : {{ vente.voiture.marque }} {{ vente.voiture.modele }}</li>
                            {% endfor %}
                        {% else %}
                            <li class="list-group-item">Aucune vente effectuée.</li>
                        {% endif %}
                    </ul>
                </div>
                <div class="col-md-6">
                    <h2 class="mt-4">Achats de l'utilisateur :</h2>
                    <ul class="list-group">
                        {% if achats|length > 0 %}
                            {% for achat in achats %}
                                <li class="list-group-item">Date d'achat : {{ achat.dateVente|date('Y-m-d') }} - Prix d'achat : {{ achat.prixVente }} - Véhicule acheté : {{ achat.voiture.marque }} {{ achat.voiture.modele }}</li>
                            {% endfor %}
                        {% else %}
                            <li class="list-group-item">Aucun achat effectué.</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-md-6">
                    <h2>Anciennes locations de l'utilisateur :</h2>
                    <ul class="list-group">
                        {% if anciennesLocations|length > 0 %}
                            {% for location in anciennesLocations %}
                                <li class="list-group-item">Date de début : {{ location.dateDebutLocation|date('Y-m-d') }} - Date de fin : {{ location.dateFinLocation|date('Y-m-d') }} - Prix total : {{ location.prixTotal }} € - Véhicule loué : {{ location.voitureLoue.marque }} {{ location.voitureLoue.modele }}</li>
                            {% endfor %}
                        {% else %}
                            <li class="list-group-item">Aucune ancienne location.</li>
                        {% endif %}
                    </ul>
                </div>
                <div class="col-md-6">
                    <h2>Nouvelles locations de l'utilisateur :</h2>
                    <ul class="list-group">
                        {% if nouvellesLocations|length > 0 %}
                            {% for location in nouvellesLocations %}
                                <li class="list-group-item">Date de début : {{ location.dateDebutLocation|date('Y-m-d') }} - Date de fin : {{ location.dateFinLocation|date('Y-m-d') }} - Prix total : {{ location.prixTotal }} € - Véhicule loué : {{ location.voitureLoue.marque }} {{ location.voitureLoue.modele }} {% if location.dateDebutLocation > dateDuJour %}<a href="{{ path('app_louer_supprimer', { 'id': location.id }) }}" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cette location ?')" class="btn btn-danger ml-2">Supprimer</a>{% endif %}</li>
                            {% endfor %}
                        {% else %}
                            <li class="list-group-item">Aucune nouvelle location.</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/profil/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Modifier Profil{% endblock %}

{% block body %}
    <main>
        <h2>Modifier Profil</h2>

        {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
        {{ form_row(form.imageProfil, {'attr': {'class': 'form-control-file'}}) }}
        <button type="submit" class="btn btn-primary">Enregistrer</button>
        {{ form_end(form) }}
    </main>
{% endblock %}